### ISSUE TITLE
Possible Issue

### ISSUE THREAD

**Issue by lostjarred** [BogdanW3/W3Diff#1]
Just slight check is this meant only for Reforged ? attempting to run on map created on Warcraft III 1.27.1.7085, results in nothing, no error message, no output of any kind  
![Capture](https://user-images.githubusercontent.com/58093147/127109905-2266fa06-61a9-4679-9be3-bd3d7d91bcc6.JPG)

**Comment by BogdanW3** [comment]
Thank you for the report, I should add error messages at least when writing to file (this program's main purpose is enhancing diffs from git, example [here](https://github.com/BogdanW3/W3DiffExample), so errors there might be disruptive)
This tool is not meant to be used on a whole map, it's meant to be used on map files separately. This is why you get no useful output neither in the file you chose nor in the terminal.

Sadly you are also correct that it is only aimed at the latest version of the game: I didn't want to add any extra files to keep the map's intended version and there are some files which cannot fully be supported without also storing data from the w3i which is not what I want for this tool so I always assume the latest version where applicable.

**Comment by lostjarred** [comment]
ah, well I was trying to figure it out that why I was trying to write to a file, I was unclear on how the tool was meant to be used the example is not that clear at least to me, I guess reforged changes how maps are saved ?(I don't much care for the HD models so stopped patching at the last downloadable patcher)

after reading that it was not meant to be used on the map archive, Figured I would try extracting the map to see if it would work and it did for some of the files, I don't know enough to say anything more, I was just curious to see it work

Anyway thanks for the quick reply
